trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5d05a2ef-c74a-47da-898a-9520334170cb'
  imageRepository: 'exrate'
  containerRegistry: 'exrate.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image names
  vmImageLinux: 'ubuntu-latest'
  vmImageWindows: 'windows-latest'

stages:
- stage: Test_and_Build
  displayName: Build and push stage
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageWindows)
    steps:
    - task: VSTest@2
      inputs:
        command: test
        projects: '**/**/*Tests/*.csproj'
        arguments: '--configuration **\$(BuildConfiguration)\*\*Tests*.dll'
        diagnosticsEnabled: true
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageLinux)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

